# Generated by Django 6.0.4 on 2026-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=120, unique=True)),
                ('phones', models.CharField(max_length=200)),
                ('syllables', models.PositiveSmallIntegerField(db_index=True)),
                ('rime', models.CharField(db_index=True, max_length=120)),
                ('rime_last1', models.CharField(db_index=True, max_length=12)),
                ('rime_last2', models.CharField(db_index=True, default='', max_length=24)),
                ('ipa_full', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['word'],
                'indexes': [models.Index(fields=['rime', 'syllables'], name='lyrichelp_d_rime_d09204_idx')],
            },
        ),
    ]
